spring:
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      authentication: TOKEN
      token: ${VAULT_TOKEN:}
      kv:
        enabled: true
        backend: secret
        application-name: aiblog
      config:
        order: -10
      fail-fast: false

vault:
  enabled: true
  uri: ${VAULT_URI:http://localhost:8200}
  token: ${VAULT_TOKEN:}
  kv:
    backend: secret
    application-name: aiblog
